parameters:
#    hospital.example.class: Salud\HospitalBundle\Example

services:
#    hospital.example:
#        class: %hospital.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
