parameters:
#    location.example.class: CP\LocationBundle\Example

services:
#    location.example:
#        class: %location.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
